name: Daily Strands Board and Data Scrape
on:
  schedule:
    - cron: '*/5 * * * *'  # Run at 00:00 CST daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager requests beautifulsoup4

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Run board scraping script
      run: python ./scripts/scrape_board.py
    
    - name: Run words scraping script
      run: python ./scripts/scrape_words.py

    - name: Run hints scraping script
      run: python ./scripts/scrape_hints.py
      
    - name: Run word defining script
      run: python ./scripts/define.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add --all
        timestamp=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
        git commit -m "Update Strands Game Data $timestamp" || exit 0
        git push
