name: Daily Strands Board and Data Scrape
on:
  schedule:
    - cron: '0 6 * * *'  # Run at 00:00 CST daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager requests beautifulsoup4

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Run scraping and defining scripts
      working-directory: ./scripts
      run: |
        python scrape_board.py
        python scrape_words.py
        python scrape_hints.py
        python define.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add --all
        timestamp=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
        git commit -m "Update Strands Game Data $timestamp" || exit 0
        git push
