name: Daily Scrape and Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run at 00:00 Midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run scraping script
      run: python ./scripts/scrape_data.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add strands_data.json
        git commit -m "Update strands data" || exit 0
        git push
